params:
  homeInfoParams:
    Title: "Hi there ðŸ‘‹"
    Content: "Can be Info, links, about..."

  socialIcons: # optional
    - name: "<platform>"
      url: "<link>"
    - name: "<platform 2>"
      url: "<link2>"

